apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090  # Ensure this is within the NodePort range (30000-32767)
  selector:
    app: prometheus
